### ISSUE TITLE
Very stupid question,how to add the dts file to armbian project...

### ISSUE THREAD

**Issue by imliubo** [nuhamind2/fbtft-dt-overlay#1]
Hi, I am new guy.Recently I am trying to use armbian to drive my LCD display, but I found that fbtft_device is no longer in the kernel. I found your post in the armbian forum, but since I am not very familiar with how to add dts file to the armbian project, I thought Ask about the specific steps. Hope to answer my question. Thank you!

**Comment by nuharaf** [comment]
I believe armbian own [documentation](https://docs.armbian.com/User-Guide_Allwinner_overlays/) is suffice here , specifically about using [custom overlay](https://docs.armbian.com/User-Guide_Allwinner_overlays/#using-custom-overlays)

**Comment by imliubo** [comment]
Thanks!I got the **/dev/fb0**, and the backlight is right,but can't display anythings.... I'm a bit confused and don't know where to start

**Comment by nuharaf** [comment]
Unfortunately there is lot of thing that can be wrong. I suggest [this post on armbian](https://forum.armbian.com/topic/13221-fbtft-with-device-tree-overlay-on-mainline/?do=findComment&comment=111424) about possible way to troubleshoot.

Also, if your lcd come with example code to be used with, say, arduino, it's good idea to test it with it, to make sure your lcd and wiring is correct.

**Comment by imliubo** [comment]
Thanks!I solved it!
![](https://makingfun.oss-cn-qingdao.aliyuncs.com/linux/armbian-learn/finally-I-got-this.png)

**Comment by nuharaf** [comment]
great, glad to help.
That nice lcd, is it sold somewhere ?

**Comment by imliubo** [comment]
In fact, I disassembled this [product](https://docs.m5stack.com/#/en/core/core2) and used its screen and casing. I think it's pretty good!And this screen also have touch!
